language: php
php:
  - '7.2'

install:
  - composer install
  - pecl install ast
  - echo "extension=ast.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - composer test-coverage
  - composer lint

after_success:
  - bash <(curl -s https://codecov.io/bash)
