language: php
php:
  - '7.2'

env:
- PHAN_ALLOW_XDEBUG=1
- PHAN_DISABLE_XDEBUG_WARN=1

install:
  - composer install
  - pecl install ast

script:
  - composer test-coverage
  - composer lint
  - composer analyze

after_success:
  - bash <(curl -s https://codecov.io/bash)
